= specifications-AA_GLOBAL

Global definitions, documents and scripts for openEHR

== How to set up the Asciidoctor publishing environment for the specifications

NOTE: a Linux-like environment is assumed; cygwin under Windows will work fine.

NOTE: in the below, if you are an openEHR SEC member, you may be doing direct clone + modify master or other branch; if you are not, you will most likely be cloning forked copies and doing pull requests in the usual way. From the point of view of publishing with Asciidoctor, there is no difference.

Firstly, you need to install asciidoctor. This is generally painless - [see here](https://asciidoctor.org).

Secondly you may need MagicDraw, since UML diagrams and definitions are extracted from the UML binary files via MagicDraw. Please contact the openEHR SEC if this is the case.

Now you need to clone the openEHR specifications repos, as follows:

1. Create a directory `openEHR-specifications` or similar to contain the specifications git repo clones
2. Download [the bash script /bin/setup_openehr_git.sh](https://github.com/openEHR/specifications-AA_GLOBAL/blob/master/bin/setup_openehr_git.sh) into that directory and run it (needs to be Linux, cygwin, or other unix-like environment).

You are now ready to go. From the parent directory, in a bash shell, type:
```
$ ./do_spec_publish -r RM
```
This will publish the HTML documents for the RM component in `specifications-RM/docs`. You can do the same for any other component, e.g. BASE, QUERY etc.

To find out what else you can do, type:
```
$ ./do_spec_publish -h
```

Whenever you want to publish changes made over time at some later date, re-run `./setup_openehr_git.sh`, which will now perform `git pull` commands on the relevant repositories, and then run `./do_spec_publish`.

== How to do a Release of a Component

Components, i.e. RM, AM, LANG, PROC etc are the units of release. Each component has its own Github repo. A release is _always named_ either:

* `Release-N.N.N`, where `N.N.N` is a semver-style 3-part release id, e.g. `1.2.14`, OR
* `Release-N.N.NvN`, where the trailing `vN` identifies a new version of the existing release `Release-N.N.N` (see below)

To do a release of a component, e.g. 'RM Release-1.0,4', the following steps are required.

=== Jira

When all the work specified by the CRs in the component project (e.g. SPECRM) in Jira is done, resolve and close all Jira CRs and PRs. You can now create the relevant saved searches for the PRs and the CRs for this release in Jira, which will have URLs of the form `<jira-home>/projects/SPECPR/versions/NNNNN` and `<jira-home>/projects/SPECR/versions/NNNNN` respectively. These are mapped in the site Apache settings as the targets of the logical URLs `/components/<COMPONENT>/Release-N.N.N/issues` and `/components/<COMPONENT>/Release-N.N.N/changes` respectively, e.g. as follows. Ask the openEHR sysadmin to add these to the rules for the `specifications.openEHR.org` site. The logical links will be generated in the specifications documentation (including the `docs/index.html`) file by the publishing process.

----
RewriteRule    ^/components/RM/Release-1.0.4/issues$      https://openehr.atlassian.net/projects/SPECPR/versions/10861    [R,L]
RewriteRule    ^/components/RM/Release-1.0.4/changes$     https://openehr.atlassian.net/projects/SPECRM/versions/11074    [R,L]
----

=== Git work area

In the Git clone work area of the relevant component, e.g. `specifications-RM`:

* make sure the document `:spec_status:` variable at the top of the `master.adoc` file of each specification is correct;
* make sure you have done every last change to the specifications files;
* now run the publisher script in release mode, e.g. `./do_spec_publish -r -l Release-1.0.4` (as many times as needed) and check:
** the HTML output front page and preface page of each specification document;
** the component index file `docs/index.html`, which is generated by `docs/index.adoc` - in particular check the release id and Jira links
* commit all the changes;
* add an _annotated_ Git tag with the release id e.g. `Release-1.0.4`, and a short description, usually of the form `"RM Release 1.0.4"`, but may have more text if needed;
* push the changes to Github.

The last push will cause a normal commit at GitHub, and the webhook will cause the openEHR.org server to do a `pull`, and then a copy out of a) the latest commit, and b) also of any tagged commit not already copied out, to two different directories under the `/var/www/vhosts/openehr.org/specifications.openehr.org/releases/COMPONENT` area, namely `Release-N.N.N` and `latest`. If you just did a release, these are the same, but otherwise, usually just the `latest` is updated. These copy-outs are what enables the `specifications.openehr.org` to serve both the latest working version and also all previous releases of any spec.

== Fixing a Release

Sometimes all the above work is performed, and then someone discovers a significant typo or other error in the newly released specifications (including diagrams etc). Fixing things is easy. Do the following in the Git work area:

* make the changes you need to the source files;
* republish using `./do_spec_publish` with the original release id, e.g. `./do_spec_publish -r -l Release-1.0.4`;
* commit the changes;
* add a new annotated tag with the id `Release-N.N.NvN+1`, e.g. `Release-1.0.4v1`; the final number must be 1 higher than the previous fix release, so it could easily be `Release-1.0.4v7` if a number of errors were discovered over time;
* push the new commit(s); the webhook-driven server scripts will over-write the last copy-out of the release with this new one;
* don't forget to merge the changes across into the component's Git repo `master` branch as well, if they are not already taken care of by changes there.

